apiVersion: v1
kind: Service
metadata:
  name: deepseek-service
spec:
  selector:
    app: deepseek
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000  # Specify a port (30000-32767)
  type: NodePort  # Use NodePort for local access
