apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-finetuned
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek
  template:
    metadata:
      labels:
        app: deepseek
    spec:
      containers:
        - name: deepseek-container
          image: deepseek-finetuned:latest  # Use local image name here
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "/app/fine_tuned_deepseek"  # Path inside the container
